In [1]:
#importing 
import pandas as pd
import matplotlib.pyplot as plt
import scipy.stats as st
import numpy as np
from scipy.stats import linregress

In [7]:
data_csv_path = "Data_csv/state_PA_avg.csv"
initial_data = pd.read_csv(data_csv_path)
del initial_data['Unnamed: 0']
del initial_data['Difference in male sufficient physical activity prevalence, 2001-2009 (percentage points)']
del initial_data['Difference in female sufficient physical activity prevalence, 2001-2009 (percentage points)']
initial_data.head()

,State,"Male sufficient physical activity prevalence, 2001 (%)","Female sufficient physical activity prevalence, 2001 (%)","Male sufficient physical activity prevalence, 2009 (%)","Female sufficient physical activity prevalence, 2009 (%)","Male sufficient physical activity prevalence, 2011* (%)","Female sufficient physical activity prevalence, 2011* (%)"
0,Alabama,52.4,40.4,51.5,41.4,49.5,42.0
1,Alaska,63.9,53.5,61.9,56.7,59.8,57.6
2,Arizona,61.3,51.8,60.9,55.2,59.5,56.9
3,Arkansas,52.4,41.4,53.6,44.3,51.3,45.2
4,California,59.4,50.7,61.4,57.0,61.3,59.2

In [15]:
PA_sum = initial_data.sum()
PA_sum = pd.DataFrame(PA_sum)
PA_sum

                                                                                                    0
State                                               AlabamaAlaskaArizonaArkansasCaliforniaColorado...
Male sufficient physical activity prevalence, 2...                                             2881.6
Female sufficient physical activity prevalence,...                                             2389.2
Male sufficient physical activity  prevalence, ...                                             2901.2
Female sufficient physical activity  prevalence...                                             2585.8
Male sufficient physical activity  prevalence, ...                                             2806.1
Female sufficient physical activity  prevalence...                                             2634.6

In [ ]:
PA_by_state = pd.DataFrame({
    "Physical activity prevalence": ne_mean,
    "Southeast": se_mean,
    "Midwest": mw_mean,
    "Southwest": sw_mean,
    "West": we_mean
})

life_by_region = life_by_region.T

In [9]:
data_csv_life = "Data_csv/state_life_avg.csv"
initial_data_life = pd.read_csv(data_csv_life)
del initial_data_life['Unnamed: 0']
del initial_data_life['Difference in male life expectancy, 1985-2010 (years)']
del initial_data_life['Difference in female life expectancy, 1985-2010 (years)']
initial_data_life.head()

,State,"Male life expectancy, 1985 (years)","Female life expectancy, 1985 (years)","Male life expectancy, 1990 (years)","Female life expectancy, 1990 (years)","Male life expectancy, 1995 (years)","Female life expectancy, 1995 (years)","Male life expectancy, 2000 (years)","Female life expectancy, 2000 (years)","Male life expectancy, 2005 (years)","Female life expectancy, 2005 (years)","Male life expectancy, 2010 (years)","Female life expectancy, 2010 (years)"
0,Alabama,69.1,76.9,69.4,77.1,69.9,77.2,71.0,77.2,71.5,77.3,72.4,77.8
1,Alaska,70.9,77.7,72.0,78.8,72.9,78.7,74.2,78.9,75.1,79.7,75.8,80.1
2,Arizona,71.7,78.8,72.3,79.3,73.1,79.6,74.5,79.9,75.2,80.5,76.8,81.7
3,Arkansas,69.8,77.5,70.2,77.6,70.6,77.8,71.8,77.8,72.2,78.0,73.0,78.5
4,California,71.7,78.3,72.3,78.8,73.5,79.6,75.7,80.3,76.5,81.2,78.2,82.5

In [6]:
life_mean = initial_data_life.mean()

In [11]:
PA_data = initial_data
PA_data

,State,"Male sufficient physical activity prevalence, 2001 (%)","Female sufficient physical activity prevalence, 2001 (%)","Male sufficient physical activity prevalence, 2009 (%)","Female sufficient physical activity prevalence, 2009 (%)","Male sufficient physical activity prevalence, 2011* (%)","Female sufficient physical activity prevalence, 2011* (%)"
0,Alabama,52.4,40.4,51.5,41.4,49.5,42.0
1,Alaska,63.9,53.5,61.9,56.7,59.8,57.6
2,Arizona,61.3,51.8,60.9,55.2,59.5,56.9
3,Arkansas,52.4,41.4,53.6,44.3,51.3,45.2
4,California,59.4,50.7,61.4,57.0,61.3,59.2
5,Colorado,64.8,56.8,65.7,61.4,64.7,62.7
6,Connecticut,58.8,50.0,59.4,53.8,57.5,54.4
7,Delaware,54.8,42.6,57.2,49.1,54.0,49.2
8,Florida,55.6,45.8,56.7,51.4,56.0,52.8
9,Georgia,53.9,41.5,56.4,49.7,54.6,50.8
10,Hawaii,68.9,55.2,68.9,59.8,66.0,60.9
11,Idaho,62.5,54.9,62.1,57.5,60.5,58.7
12,Illinois,54.0,43.4,56.7,52.7,54.8,54.2
13,Indiana,56.1,45.2,54.6,46.6,52.5,47.6
14,Iowa,56.0,46.6,56.4,51.7,54.1,52.9
15,Kansas,54.8,46.2,56.6,50.1,53.5,50.5
16,Kentucky,44.5,33.6,51.3,44.0,49.9,45.8
17,Louisiana,47.7,36.4,51.9,42.0,49.8,42.8
18,Maine,60.4,53.3,62.4,58.1,60.7,59.0
19,Maryland,59.1,47.6,57.2,51.2,55.4,51.7
20,Massachusetts,60.9,50.9,59.9,54.3,59.6,55.7
21,Michigan,57.7,48.6,59.2,52.8,57.8,53.8
22,Minnesota,61.5,53.9,61.1,55.6,59.8,56.8
23,Mississippi,48.4,35.7,49.6,38.8,47.2,39.7
24,Missouri,55.7,45.6,55.5,49.3,53.6,50.3
25,Montana,62.1,54.9,62.4,57.9,60.4,58.5
26,Nebraska,55.1,45.0,57.0,52.1,53.7,52.7
27,Nevada,60.0,49.8,57.6,50.6,56.3,51.6
28,New Hampshire,64.4,54.9,62.8,57.5,61.0,57.9
29,New Jersey,54.9,44.2,57.1,50.0,56.2,51.9
30,New Mexico,60.2,50.5,60.4,53.6,57.8,54.5
31,New York,53.3,44.3,56.3,49.4,55.3,50.8
32,North Carolina,54.4,42.0,56.1,47.3,54.3,48.2
33,North Dakota,56.1,49.4,56.8,52.4,53.7,52.8
34,Ohio,56.8,45.6,57.1,49.6,55.4,50.9
35,Oklahoma,50.7,41.1,53.0,46.0,50.6,46.7
36,Oregon,65.2,56.6,64.0,60.9,63.2,62.4
37,Pennsylvania,57.1,48.0,57.8,50.4,55.8,51.2
38,Rhode Island,58.2,48.2,56.4,50.2,54.7,50.5
39,South Carolina,58.0,43.3,57.1,48.0,55.1,49.1
40,South Dakota,54.2,49.0,54.9,51.1,52.3,52.0
41,Tennessee,48.8,36.3,48.8,39.2,46.7,39.9
42,Texas,55.2,44.1,56.4,48.4,54.1,49.5
43,Utah,64.1,56.4,63.5,57.4,60.2,57.6
44,Vermont,65.3,58.2,65.1,61.8,63.7,62.8
45,Virginia,59.7,47.0,58.0,52.6,56.4,53.6
46,Washington,65.9,58.0,63.2,59.0,61.2,60.0
47,West Virginia,52.1,42.2,50.3,41.8,47.8,42.4
48,Wisconsin,62.1,53.4,60.7,56.5,59.5,57.7
49,Wyoming,62.2,55.2,60.3,57.6,57.3,58.2